import { useEffect, useState } from 'react';
import { ArrowUpRight, CalendarDays, Check, ChevronRight, History, ScanLine, ShieldAlert, Store } from 'lucide-react';
import { Link } from 'react-router-dom';
import { getHistory, requestVendorAccess } from '../api/api';
import { useAuth } from '../context/AuthContext';

export default function Dashboard() {
  const { user, loading, setUser } = useAuth(); const [items, setItems] = useState([]); const [state, setState] = useState('loading'); const [vendorBusy, setVendorBusy] = useState(false);
  useEffect(() => { if (!user) return; let active = true; getHistory().then(value => { if (active) { setItems(Array.isArray(value) ? value : (value?.items || value?.history || [])); setState('ready'); } }).catch(() => { if (active) setState('error'); }); return () => { active = false; }; }, [user]);
  const fresh = items.filter(item => item.status === 'fresh').length; const rotten = items.filter(item => item.status === 'rotten').length;
  if (!loading && !user) return <main className="empty-page"><History size={34} /><h1>Your dashboard awaits.</h1><p>Sign in to see your saved freshness checks and scan history.</p><Link to="/signin" className="primary-button">Sign in <ChevronRight size={16} /></Link></main>;
  const becomeVendor = async () => { setVendorBusy(true); try { const result = await requestVendorAccess(); setUser({ ...user, role: result.role }); } finally { setVendorBusy(false); } };
  return <main className="page-shell dashboard-page"><div className="dashboard-heading"><div><p className="eyebrow">Your dashboard</p><h1>A clearer view<br /><em>of your fruit.</em></h1><p>Review recent checks and start a new one when you are ready.</p></div><Link className="primary-button" to="/detect"><ScanLine size={17} /> Scan a new fruit</Link></div>{user.role === 'customer' && <section className="vendor-prompt"><Store size={22} /><div><strong>Run checks at business scale?</strong><p>Request vendor access for batch scanning and exportable reports.</p></div><button className="secondary-button" onClick={becomeVendor} disabled={vendorBusy}>{vendorBusy ? 'Activating...' : 'Request vendor access'}</button></section>}<div className="stat-grid"><article><span>Total scans</span><strong>{state === 'loading' ? '--' : items.length}</strong><small>All saved checks</small></article><article><span>Fresh</span><strong>{state === 'loading' ? '--' : fresh}</strong><small><Check size={13} /> Good candidates</small></article><article><span>Needs attention</span><strong>{state === 'loading' ? '--' : rotten}</strong><small><ShieldAlert size={13} /> Review carefully</small></article></div><section className="recent-section"><div className="section-heading"><div><p className="eyebrow">Latest activity</p><h2>Recent scans</h2></div><Link to="/history" className="text-button">View all <ArrowUpRight size={15} /></Link></div>{state === 'loading' ? <div className="dashboard-list-skeleton"><span /><span /><span /></div> : state === 'error' ? <div className="inline-error">We could not load your saved scans. Refresh and try again.</div> : items.length ? <div className="dashboard-list">{items.slice(0, 4).map(item => <article className="dashboard-item" key={item.id}>{item.image_url ? <img src={`${import.meta.env.VITE_API_URL?.replace('/api', '') || 'http://127.0.0.1:8000'}${item.image_url}`} alt={item.fruit} /> : <div className="history-thumb">{item.fruit[0]}</div>}<div><strong>{item.fruit}</strong><span><CalendarDays size={13} /> {new Date(item.created_at).toLocaleDateString()}</span></div><div className={`history-status ${item.status}`}>{item.status === 'fresh' ? 'Fresh' : 'Rotten'} <small>{item.confidence}%</small></div></article>)}</div> : <div className="dashboard-empty"><History size={27} /><div><strong>No scans yet</strong><p>Upload a photo to create your first freshness record.</p></div><Link className="secondary-button" to="/detect">Start a scan</Link></div>}</section></main>;
}
